#+TITLE: This is a title
#+TODO: TODO PLAY | DONE MNORGE

# This is just a regular comment.  Nothing to see here!
# As you can see, comments can be smushed together
     # Comments can have indentation, but the scanner doesn't really care.

# With text in between

Welcome to my homepage, there are many like it, but this one is mine!

# This is a comment at the end of the line


#+begin_src emacs-lisp server
;; *** This is a headline at the beginning of a lisp section
(defun foo ()
  (message "hello from foo"))
#+end_src

*                  This is a title :fun:work:stuff:

#+KEY[OPTIONAL]: VALUE
** PLAY This is another title :work_oiuo:foo:bar:

#+ This is just a comment, not a keyword
#+K: On the other hand, this is a keyword

This is some other text

:PROPERTIES:
:STYLE:    slurm
:END:

This is some text right here.  Before the drawer
#This is not a comment, but a bit of regular text

#+BEGIN
This some stuff in a block
#+END


    :foo:
    :GAGA: blorb
    :END:

    :bar1-_-'$%:
    this is some stuff in here
    :END:

*** This is a third title :play:
I would like to thank the Academy for this award.  Being an actor I will likely talk for far too long.

Why?  Because reasons.

I am trained in the art of talking.  I can do it well, all my teachers are proud of me.  I can go on about
a great many subjects and I'm more interesting than the average Joe in conversation.  Since I appear in movies
and TV shows you know me, and many of you like me.  Therefore, you will likely be interested in what I have to say.

These days I mostly worry about my Slipstream RV.  It's a beaut, but I could use an upgrade.  If anyone is interested
let me know and we can work out a deal.
*** MNORGE Floombo!
**** Whoa!
